// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJc7xWrjfQL4WcEB7nhvlfa3Zqfek1YI8',
    appId: '1:150344300975:web:a7cd83ca456dddd04fd75a',
    messagingSenderId: '150344300975',
    projectId: 'stubwin-df617',
    authDomain: 'stubwin-df617.firebaseapp.com',
    storageBucket: 'stubwin-df617.appspot.com',
    measurementId: 'G-M7FY9W5NEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9lE0UpacaWhVi0vGSOgD_UIDqsh8nSM',
    appId: '1:150344300975:android:df26a6a93965f3ea4fd75a',
    messagingSenderId: '150344300975',
    projectId: 'stubwin-df617',
    storageBucket: 'stubwin-df617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC971i50W85hG36CJbkl18QOiIxlmkQ8Ac',
    appId: '1:150344300975:ios:16beeb21fcf77b7c4fd75a',
    messagingSenderId: '150344300975',
    projectId: 'stubwin-df617',
    storageBucket: 'stubwin-df617.appspot.com',
    iosClientId: '150344300975-be3g93v73mpgtha0ejdof6gjckl5bh3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.stubWindow',
  );
}
